---
- name: Install required packages
  ansible.builtin.package:
    name:
      - nginx
      - python3
      - python3-pip
    state: present

- name: Install flask and gunicorn
  ansible.builtin.pip:
    name:
      - flask
      - gunicorn
